# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Music Recommendation Agent using Graph Workflow."""

import json
import os
from typing import Any, AsyncGenerator

import google.auth
from google.adk.agents import Agent
from google.adk.agents.context import Context
from google.adk.apps import App
from google.adk.events.event import Event
from google.adk.models import Gemini
from google.adk.workflow import Workflow
from google.genai import Client, types
from pydantic import BaseModel, Field

from app.tools import retrieve_lyrics_theme, retrieve_music_metadata, verify_song_exists

# Setup Google Cloud project credentials for the Google GenAI SDK
try:
    _, project_id = google.auth.default()
    os.environ["GOOGLE_CLOUD_PROJECT"] = project_id
    os.environ["GOOGLE_CLOUD_LOCATION"] = "global"
    os.environ["GOOGLE_GENAI_USE_VERTEXAI"] = "True"
except Exception:
    pass


# ---------------------------------------------------------------------------
# Pydantic schemas for structured data flow
# ---------------------------------------------------------------------------


class WavelengthInput(BaseModel):
    """Input structure for the Wavelength workflow."""

    seed_song: str = Field(description="The song name and optional artist to analyze.")
    target_mood: str = Field(description="The user's target mood for recommendations.")


class SongProfile(BaseModel):
    """Synthesized analysis and factual metadata of the seed song."""

    title: str = Field(description="The title of the song.")
    artist: str = Field(description="The artist of the song.")
    tempo: int = Field(description="The tempo of the song in BPM (beats per minute).")
    genre: str = Field(description="The genre of the song.")
    key: str = Field(description="The musical key of the song (e.g. C Major).")
    release_year: int = Field(description="The year the song was released.")
    lyrics_theme: str = Field(description="The key themes/lyrics interpretations of the song.")


class MoodAlignmentOutput(BaseModel):
    """Decision output for recommended strategy."""

    strategy: str = Field(description="Recommendation strategy: 'mood_match' or 'mood_shift'.")
    reasoning: str = Field(description="The detailed reasoning behind the chosen strategy.")


class CandidateRecommendation(BaseModel):
    """Structure representing a single recommended candidate song."""

    title: str = Field(description="The recommended song title.")
    artist: str = Field(description="The recommended song artist.")
    reason: str = Field(description="Content-based explanation of why this song matches.")


class GeneratedCandidates(BaseModel):
    """Intermediate list of up to 5 recommendations generated by LLM reasoning."""

    candidates: list[CandidateRecommendation] = Field(description="List of song recommendations.")


class CandidateVerifierOutput(BaseModel):
    """Final output schema containing verified recommendations.

    Note: Unverified candidates are silently filtered and dropped from
    the recommendations list without raising an error or surfacing
    a failure message to the user.
    """

    recommendations: list[CandidateRecommendation] = Field(description="List of verified song recommendations.")


# ---------------------------------------------------------------------------
# Graph Workflow Nodes
# ---------------------------------------------------------------------------


def song_understanding(node_input: WavelengthInput, ctx: Context) -> AsyncGenerator[Event, None]:
    """Node 1: Retrieves music metadata and lyric themes, and synthesizes into a SongProfile."""
    # Store target mood in state for downstream nodes
    ctx.state["target_mood"] = node_input.target_mood

    # Separate search-grounded tool calls
    metadata = retrieve_music_metadata(node_input.seed_song)
    lyrics_theme = retrieve_lyrics_theme(node_input.seed_song)

    # Synthesize outputs using Gemini client
    client = Client()
    prompt = f"""Synthesize the following retrieved music metadata and lyric/theme interpretations for the seed song "{node_input.seed_song}" into a structured SongProfile.

Factual Metadata:
{json.dumps(metadata, indent=2)}

Lyric/Theme Interpretations:
{json.dumps(lyrics_theme, indent=2)}

Do NOT make up or generate any metadata or interpretations from your own unretrieved knowledge. Use the provided information.
Return the result strictly according to the SongProfile schema."""

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema=SongProfile,
        ),
    )
    profile = SongProfile.model_validate_json(response.text)

    # Save to state for later retrieval in verification
    ctx.state["song_profile"] = profile.model_dump()

    # Renders in ADK UI / CLI output
    msg = (
        f"🎵 **Seed Song Profile Analysis:**\n"
        f"- **Title**: {profile.title} by *{profile.artist}*\n"
        f"- **Tempo**: {profile.tempo} BPM | **Key**: {profile.key} | **Release**: {profile.release_year}\n"
        f"- **Genre**: {profile.genre}\n"
        f"- **Lyric Interpretation/Themes**: {profile.lyrics_theme}"
    )
    yield Event(content=types.Content(role="model", parts=[types.Part.from_text(text=msg)]))
    yield Event(output=profile)


def mood_alignment(node_input: SongProfile, ctx: Context) -> AsyncGenerator[Event, None]:
    """Node 2: Decides the recommendation strategy (mood_match or mood_shift)."""
    target_mood = ctx.state.get("target_mood", "")

    client = Client()
    prompt = f"""Given the song profile:
{node_input.model_dump_json()}

And the target mood specified by the user: "{target_mood}"

Decide whether the recommendation strategy should be:
- "mood_match": find similar-feeling songs to the seed song if the seed song already aligns well with the target mood.
- "mood_shift": find songs to shift the mood if the seed song is different from the target mood and we need to transition.

Provide your decision and detailed reasoning.
Return the result strictly according to the MoodAlignmentOutput schema."""

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema=MoodAlignmentOutput,
        ),
    )
    result = MoodAlignmentOutput.model_validate_json(response.text)

    msg = f"🎯 **Strategy decision:** `{result.strategy}`\n**Reasoning:** {result.reasoning}"
    yield Event(content=types.Content(role="model", parts=[types.Part.from_text(text=msg)]))
    yield Event(output=result)


def candidate_verifier(node_input: MoodAlignmentOutput, ctx: Context) -> AsyncGenerator[Event, None]:
    """Node 3: Generates up to 5 recommendations, verifies their existence via search, and silently drops unverified candidates."""
    song_profile_dict = ctx.state.get("song_profile", {})
    song_profile = SongProfile(**song_profile_dict)

    # Step 1: Generate up to 5 candidate recommendations via LLM reasoning
    client = Client()
    prompt = f"""Based on the seed song profile:
{song_profile.model_dump_json()}

And the decided recommendation strategy: "{node_input.strategy}"
Reasoning: "{node_input.reasoning}"

Generate up to 5 candidate song recommendations using content-based filtering.
Match them based on tempo, genre, and themes. Do not use personal listening history.
Return the result strictly according to the GeneratedCandidates schema."""

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema=GeneratedCandidates,
        ),
    )
    candidates_data = GeneratedCandidates.model_validate_json(response.text)

    # Step 2: Verify each candidate via verify_song_exists tool
    verified_recs = []
    for candidate in candidates_data.candidates:
        if verify_song_exists(candidate.title, candidate.artist):
            verified_recs.append(candidate)
        else:
            # Unverified candidates are silently filtered/dropped without error
            pass

    msg = f"🎶 **Verified Recommendations (Strategy: {node_input.strategy}):**\n\n"
    if verified_recs:
        for idx, rec in enumerate(verified_recs, 1):
            msg += f"{idx}. **{rec.title}** by *{rec.artist}*\n   *Reason*: {rec.reason}\n"
    else:
        msg += "*No candidates could be verified as existing via search grounding.*"

    yield Event(content=types.Content(role="model", parts=[types.Part.from_text(text=msg)]))
    yield Event(output=CandidateVerifierOutput(recommendations=verified_recs))


# ---------------------------------------------------------------------------
# Graph definition and App Configuration
# ---------------------------------------------------------------------------

root_agent = Workflow(
    name="wavelength_recommendation_graph",
    input_schema=WavelengthInput,
    output_schema=CandidateVerifierOutput,
    edges=[
        ("START", song_understanding),
        (song_understanding, mood_alignment),
        (mood_alignment, candidate_verifier),
    ],
    description="A music recommendation workflow that analyzes a seed song, aligns target mood, generates recommendations, and verifies candidates exist.",
)

app = App(
    root_agent=root_agent,
    name="app",
)
